services:
  dashboard:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    container_name: dashboard
    ports:
      - '5173:5173'
    volumes:
      - .:/dashboard
